import React from 'react';
import WorldMapRenderer from "../../content/maps/worldMap";
import InitialMapRenderer from "../../content/maps/initialMap/initialMap";
import { 
  EntranceRenderer,
  ReceptionRenderer,
  SecurityRenderer,
  ConferenceRoomsRenderer,
  EngineeringRenderer,
  FoundryRenderer,
  WestHallsRenderer,
  EastHallsRenderer
} from "../../content/maps/initialMap/rooms";

export default function getMapData(mapId) { return mapList[mapId]; }

export const mapList = [

  // world map
  {
    id: 0,
    name: 'Test World Map',
    renderer: () => <WorldMapRenderer />,
    locations: [
      { id: 0, name: 'Safehouse', description: 'A place where you can rest and work safely. For now.', left: null, top: null, layer: 'physical', renderer: null, contacts: ['Friend One', 'Friend Two'], expeditions: ['Perimeter Breach'], newProjects: ['Research Something', 'Craft Something'], ongoingProjects: ['Research This', 'Craft That', 'Network Here', 'Solve This Mystery'] },
      { id: 1, name: 'Onett', description: 'The first town.', left: 32, top: 36, width: null, height: null, layer: 'physical', renderer: null, contacts: ['Friend 3'], expeditions: [], newProjects: [], ongoingProjects: [] },
      { id: 2, name: 'Twoson', description: 'The second town.', left: 52, top: 57, layer: 'physical', renderer: null, contacts: [], expeditions: [], newProjects: ['Network Here'], ongoingProjects: []},
      { id: 3, name: 'Threed', description: 'The third town.', left: 38, top: 67, layer: 'yau', renderer: null, contacts: [], expeditions: ['A Boss Fight'], newProjects: [], ongoingProjects: ['Identify Weaknesses'] },
      { id: 4, name: 'Fourside', description: 'The fourth town.', left: 68, top: 24, layer: 'simulation', renderer: null, contacts: ['A Mysterious Stranger'], expeditions: [], newProjects: [], ongoingProjects: [] },
      { id: 5, name: 'Fivelton', description: 'The fifth town', left: 51, top: 84, layer: 'physical', renderer: null, contacts: [], expeditions: ['A Huge Dungeon'], newProjects: [], ongoingProjects: [] },
    ],
  },

  // initial map
  {
    id: 1,
    name: 'Test Exploration Map',
    background: '#000000',
    renderer: () => <InitialMapRenderer />,
    locations: [
      { 
        id: 0,
        name: 'Entrance',
        description: 'Another room.',
        left: 39.2, top: 68.7, width: 9.5, height: 8,
        layer: 'physical',
        adjacentTo: [2, 6],
        contacts: ['Friend 3'],
        expeditions: [],
        newProjects: [],
        ongoingProjects: [],
        renderer: () => <EntranceRenderer />,
      },
      { 
        id: 1,
        name: 'Reception',
        description: 'A room',
        left: 21.6, top: 72, width: 15, height: 20,
        adjacentTo: [6],
        layer: 'physical',
        contacts: ['Friend One', 'Friend Two'],
        expeditions: ['Perimeter Breach'],
        newProjects: ['Research Something', 'Craft Something'],
        ongoingProjects: ['Research This', 'Craft That'],
        renderer: () => <ReceptionRenderer />,
      },
      { 
        id: 2,
        name: 'Security',
        description: '3rd room.',
        left: 46.3, top: 73, width: 5, height: 7,
        adjacentTo: [0, 7],
        layer: 'physical',
        contacts: [],
        expeditions: [],
        newProjects: ['Network Here'],
        ongoingProjects: [],
        renderer: () => <SecurityRenderer />,
      },
      { 
        id: 3,
        name: 'Conference Rooms',
        description: 'Another room.',
        left: 14.1, top: 54.6, width: 24.8, height: 30,
        adjacentTo: [6],
        layer: 'physical',
        contacts: [],
        expeditions: [],
        newProjects: [],
        ongoingProjects: [],
        renderer: () => <ConferenceRoomsRenderer />,
      },
      { 
        id: 4,
        name: 'Engineering',
        description: 'Another room.',
        left: 51, top: 66, width: 34, height: 17,
        adjacentTo: [7],
        layer: 'physical',
        contacts: [],
        expeditions: [],
        newProjects: [],
        ongoingProjects: [],
        renderer: () => <EngineeringRenderer />,
      },
      { 
        id: 5,
        name: 'Circuit Foundry',
        description: 'Another room.',
        left: 56.4, top: 54.6, width: 28.8, height: 11,
        adjacentTo: [7],
        layer: 'physical',
        contacts: [],
        expeditions: [],
        newProjects: [],
        ongoingProjects: [],
        renderer: () => <FoundryRenderer />,
      },
      { 
        id: 6,
        name: 'West Halls',
        description: 'Another room.',
        left: 14.7, top: 67, width: 24.2, height: 28,
        adjacentTo: [0, 1, 3],
        layer: 'physical',
        contacts: [],
        expeditions: [],
        newProjects: [],
        ongoingProjects: [],
        renderer: () => <WestHallsRenderer />,
      },
      { 
        id: 7,
        name: 'East Halls',
        description: 'Another room.',
        left: 46.1, top: 54.6, width: 39.2, height: 22,
        adjacentTo: [2, 4, 5],
        layer: 'physical',
        contacts: [],
        expeditions: [],
        newProjects: [],
        ongoingProjects: [],
        renderer: () => <EastHallsRenderer />,
      },
    ],
  }
];